#define _GNU_SOURCE
#include "kira_wayland.h"

#include <poll.h>

#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <wayland-client.h>

#include "cursor-shape-v1-client-protocol.h"
#include "viewporter-client-protocol.h"
#include "xdg-decoration-client-protocol.h"
#include "xdg-shell-client-protocol.h"

void *kira_wayland_display_connect(void) { return wl_display_connect(NULL); }
void kira_wayland_display_disconnect(void *display) { wl_display_disconnect(display); }
int32_t kira_wayland_display_roundtrip(void *display) { return wl_display_roundtrip(display); }
int32_t kira_wayland_display_flush(void *display) { return wl_display_flush(display); }
int32_t kira_wayland_display_dispatch_pending(void *display) { return wl_display_dispatch_pending(display); }
int32_t kira_wayland_display_pump(void *display) {
    struct wl_display *wl_display = display;

    // prepare_read refuses while decoded events are still queued. Drain those
    // first, then reserve the socket read so no event can race between the
    // pending check and poll.
    while (wl_display_prepare_read(wl_display) != 0) {
        if (wl_display_dispatch_pending(wl_display) < 0) return -1;
    }

    // Requests generated by the last frame must reach the compositor before
    // checking for its replies. EAGAIN is harmless for a nonblocking pump; the
    // next frame retries it.
    wl_display_flush(wl_display);

    struct pollfd source = {
        .fd = wl_display_get_fd(wl_display),
        .events = POLLIN,
        .revents = 0,
    };
    int ready = poll(&source, 1, 0);
    if (ready > 0 && (source.revents & POLLIN)) {
        if (wl_display_read_events(wl_display) < 0) return -1;
        return wl_display_dispatch_pending(wl_display);
    }

    wl_display_cancel_read(wl_display);
    return ready < 0 ? -1 : 0;
}

void *kira_wayland_display_get_registry(void *display) { return wl_display_get_registry(display); }
void *kira_wayland_registry_bind_compositor(void *registry, uint32_t name, uint32_t version) {
    return wl_registry_bind(registry, name, &wl_compositor_interface, version);
}
void *kira_wayland_registry_bind_shell(void *registry, uint32_t name, uint32_t version) {
    return wl_registry_bind(registry, name, &xdg_wm_base_interface, version);
}
void *kira_wayland_registry_bind_decoration_manager(void *registry, uint32_t name, uint32_t version) {
    return wl_registry_bind(registry, name, &zxdg_decoration_manager_v1_interface, version);
}
void *kira_wayland_registry_bind_seat(void *registry, uint32_t name, uint32_t version) {
    return wl_registry_bind(registry, name, &wl_seat_interface, version);
}
struct kira_wayland_cursor_shape_bind {
    void *manager;
};

static void kira_wayland_cursor_shape_global(
    void *data,
    struct wl_registry *registry,
    uint32_t name,
    const char *interface,
    uint32_t version
) {
    struct kira_wayland_cursor_shape_bind *bind = data;
    if (bind->manager || strcmp(interface, "wp_cursor_shape_manager_v1") != 0) return;
    uint32_t bind_version = version > 1 ? 1 : version;
    bind->manager = wl_registry_bind(
        registry,
        name,
        &wp_cursor_shape_manager_v1_interface,
        bind_version
    );
}

static void kira_wayland_cursor_shape_global_remove(
    void *data,
    struct wl_registry *registry,
    uint32_t name
) {
    (void)data;
    (void)registry;
    (void)name;
}

void *kira_wayland_display_bind_cursor_shape_manager(void *display) {
    struct wl_registry *registry = wl_display_get_registry(display);
    if (!registry) return NULL;
    struct kira_wayland_cursor_shape_bind bind = {0};
    const struct wl_registry_listener listener = {
        .global = kira_wayland_cursor_shape_global,
        .global_remove = kira_wayland_cursor_shape_global_remove,
    };
    wl_registry_add_listener(registry, &listener, &bind);
    if (wl_display_roundtrip(display) < 0) bind.manager = NULL;
    wl_registry_destroy(registry);
    return bind.manager;
}

int32_t kira_wayland_registry_add_listener(void *registry, const struct kira_wayland_registry_listener *listener, void *data) {
    return wl_registry_add_listener(registry, (const struct wl_registry_listener *)listener, data);
}
int32_t kira_wayland_shell_add_listener(void *shell, const struct kira_wayland_shell_listener *listener, void *data) {
    return xdg_wm_base_add_listener(shell, (const struct xdg_wm_base_listener *)listener, data);
}
int32_t kira_wayland_surface_add_listener(void *surface, const struct kira_wayland_surface_listener *listener, void *data) {
    return xdg_surface_add_listener(surface, (const struct xdg_surface_listener *)listener, data);
}
int32_t kira_wayland_toplevel_add_listener(void *toplevel, const struct kira_wayland_toplevel_listener *listener, void *data) {
    return xdg_toplevel_add_listener(toplevel, (const struct xdg_toplevel_listener *)listener, data);
}
int32_t kira_wayland_seat_add_listener(void *seat, const struct kira_wayland_seat_listener *listener, void *data) {
    return wl_seat_add_listener(seat, (const struct wl_seat_listener *)listener, data);
}
int32_t kira_wayland_pointer_add_listener(void *pointer, const struct kira_wayland_pointer_listener *listener, void *data) {
    return wl_pointer_add_listener(pointer, (const struct wl_pointer_listener *)listener, data);
}

void *kira_wayland_compositor_create_surface(void *compositor) { return wl_compositor_create_surface(compositor); }
void *kira_wayland_shell_get_surface(void *shell, void *surface) { return xdg_wm_base_get_xdg_surface(shell, surface); }
void *kira_wayland_surface_get_toplevel(void *surface) { return xdg_surface_get_toplevel(surface); }
void *kira_wayland_seat_get_pointer(void *seat) { return wl_seat_get_pointer(seat); }
void *kira_wayland_cursor_shape_manager_get_pointer(void *manager, void *pointer) {
    return wp_cursor_shape_manager_v1_get_pointer(manager, pointer);
}
void *kira_wayland_decoration_get_toplevel(void *manager, void *toplevel) {
    return zxdg_decoration_manager_v1_get_toplevel_decoration(manager, toplevel);
}

void kira_wayland_shell_pong(void *shell, uint32_t serial) { xdg_wm_base_pong(shell, serial); }
void kira_wayland_surface_ack_configure(void *surface, uint32_t serial) { xdg_surface_ack_configure(surface, serial); }
void kira_wayland_toplevel_set_title(void *toplevel, const char *title) { xdg_toplevel_set_title(toplevel, title); }
void kira_wayland_toplevel_set_app_id(void *toplevel, const char *app_id) { xdg_toplevel_set_app_id(toplevel, app_id); }
void kira_wayland_toplevel_move(void *toplevel, void *seat, uint32_t serial) { xdg_toplevel_move(toplevel, seat, serial); }
void kira_wayland_toplevel_resize(void *toplevel, void *seat, uint32_t serial, uint32_t edges) { xdg_toplevel_resize(toplevel, seat, serial, edges); }
void kira_wayland_toplevel_set_minimized(void *toplevel) { xdg_toplevel_set_minimized(toplevel); }
void kira_wayland_toplevel_set_maximized(void *toplevel) { xdg_toplevel_set_maximized(toplevel); }
void kira_wayland_toplevel_unset_maximized(void *toplevel) { xdg_toplevel_unset_maximized(toplevel); }
int32_t kira_wayland_toplevel_states_contains(void *states, uint32_t expected) {
    if (!states) return 0;
    uint32_t *state;
    wl_array_for_each(state, (struct wl_array *)states) {
        if (*state == expected) return 1;
    }
    return 0;
}
uint32_t kira_wayland_toplevel_state_maximized(void) { return XDG_TOPLEVEL_STATE_MAXIMIZED; }
uint32_t kira_wayland_toplevel_state_activated(void) { return XDG_TOPLEVEL_STATE_ACTIVATED; }
void kira_wayland_cursor_shape_device_set_shape(void *device, uint32_t serial, uint32_t shape) {
    wp_cursor_shape_device_v1_set_shape(device, serial, shape);
}
uint32_t kira_wayland_cursor_shape_default(void) { return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT; }
uint32_t kira_wayland_cursor_shape_for_resize_edge(uint32_t edges) {
    switch (edges) {
        case XDG_TOPLEVEL_RESIZE_EDGE_TOP: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_N_RESIZE;
        case XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_S_RESIZE;
        case XDG_TOPLEVEL_RESIZE_EDGE_LEFT: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_W_RESIZE;
        case XDG_TOPLEVEL_RESIZE_EDGE_RIGHT: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_E_RESIZE;
        case XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NW_RESIZE;
        case XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NE_RESIZE;
        case XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SW_RESIZE;
        case XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_SE_RESIZE;
        default: return WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT;
    }
}
uint32_t kira_wayland_resize_edge_top(void) { return XDG_TOPLEVEL_RESIZE_EDGE_TOP; }
uint32_t kira_wayland_resize_edge_bottom(void) { return XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM; }
uint32_t kira_wayland_resize_edge_left(void) { return XDG_TOPLEVEL_RESIZE_EDGE_LEFT; }
uint32_t kira_wayland_resize_edge_top_left(void) { return XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT; }
uint32_t kira_wayland_resize_edge_bottom_left(void) { return XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT; }
uint32_t kira_wayland_resize_edge_right(void) { return XDG_TOPLEVEL_RESIZE_EDGE_RIGHT; }
uint32_t kira_wayland_resize_edge_top_right(void) { return XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT; }
uint32_t kira_wayland_resize_edge_bottom_right(void) { return XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT; }
void kira_wayland_decoration_set_server_side(void *decoration) {
    zxdg_toplevel_decoration_v1_set_mode(decoration, ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
}
void kira_wayland_surface_commit(void *surface) { wl_surface_commit(surface); }
void kira_wayland_surface_set_window_geometry(void *xdg_surface, int32_t x, int32_t y, int32_t width, int32_t height) {
    xdg_surface_set_window_geometry(xdg_surface, x, y, width, height);
}

enum { KIRA_WAYLAND_RESIZE_MARGIN = 7, KIRA_WAYLAND_RESIZE_ZONE_COUNT = 8 };

struct kira_wayland_resize_globals {
    struct wl_subcompositor *subcompositor;
    struct wl_shm *shm;
    struct wp_viewporter *viewporter;
};

struct kira_wayland_resize_frame {
    struct wl_surface *root;
    struct xdg_surface *xdg_surface;
    struct wl_buffer *buffer;
    struct wl_shm_pool *pool;
    struct wl_surface *zones[KIRA_WAYLAND_RESIZE_ZONE_COUNT];
    struct wl_subsurface *subsurfaces[KIRA_WAYLAND_RESIZE_ZONE_COUNT];
    struct wp_viewport *viewports[KIRA_WAYLAND_RESIZE_ZONE_COUNT];
    uint32_t edges[KIRA_WAYLAND_RESIZE_ZONE_COUNT];
    int32_t offsets_x[KIRA_WAYLAND_RESIZE_ZONE_COUNT];
    int32_t offsets_y[KIRA_WAYLAND_RESIZE_ZONE_COUNT];
    struct kira_wayland_resize_frame *next;
};

static struct kira_wayland_resize_frame *kira_wayland_resize_frames;

static void kira_wayland_resize_global(
    void *data, struct wl_registry *registry, uint32_t name,
    const char *interface, uint32_t version
) {
    struct kira_wayland_resize_globals *globals = data;
    if (strcmp(interface, "wl_subcompositor") == 0) {
        globals->subcompositor = wl_registry_bind(registry, name, &wl_subcompositor_interface, 1);
    } else if (strcmp(interface, "wl_shm") == 0) {
        globals->shm = wl_registry_bind(registry, name, &wl_shm_interface, version > 1 ? 1 : version);
    } else if (strcmp(interface, "wp_viewporter") == 0) {
        globals->viewporter = wl_registry_bind(registry, name, &wp_viewporter_interface, 1);
    }
}

static void kira_wayland_resize_global_remove(void *data, struct wl_registry *registry, uint32_t name) {
    (void)data; (void)registry; (void)name;
}

static struct kira_wayland_resize_frame *kira_wayland_resize_frame_find(void *surface) {
    struct kira_wayland_resize_frame *frame = kira_wayland_resize_frames;
    while (frame && frame->root != surface) frame = frame->next;
    return frame;
}

static void kira_wayland_resize_zone_geometry(
    struct kira_wayland_resize_frame *frame, int index,
    int32_t x, int32_t y, int32_t width, int32_t height
) {
    if (width < 1) width = 1;
    if (height < 1) height = 1;
    frame->offsets_x[index] = x;
    frame->offsets_y[index] = y;
    wl_subsurface_set_position(frame->subsurfaces[index], x, y);
    wp_viewport_set_destination(frame->viewports[index], width, height);
    wl_surface_attach(frame->zones[index], frame->buffer, 0, 0);
    wl_surface_damage(frame->zones[index], 0, 0, width, height);
    wl_surface_commit(frame->zones[index]);
}

void kira_wayland_resize_frame_update(void *surface, int32_t width, int32_t height) {
    struct kira_wayland_resize_frame *frame = kira_wayland_resize_frame_find(surface);
    if (!frame || width < 1 || height < 1) return;
    // The compositor's placement/shadow bounds are the visible content, never
    // the transparent input subsurfaces surrounding it. This is pending surface
    // state and must follow every configured size, not just the initial one.
    xdg_surface_set_window_geometry(frame->xdg_surface, 0, 0, width, height);
    const int32_t m = KIRA_WAYLAND_RESIZE_MARGIN;
    kira_wayland_resize_zone_geometry(frame, 0, 0, -m, width, m);
    kira_wayland_resize_zone_geometry(frame, 1, 0, height, width, m);
    kira_wayland_resize_zone_geometry(frame, 2, -m, 0, m, height);
    kira_wayland_resize_zone_geometry(frame, 3, width, 0, m, height);
    kira_wayland_resize_zone_geometry(frame, 4, -m, -m, m, m);
    kira_wayland_resize_zone_geometry(frame, 5, width, -m, m, m);
    kira_wayland_resize_zone_geometry(frame, 6, -m, height, m, m);
    kira_wayland_resize_zone_geometry(frame, 7, width, height, m, m);
}

int32_t kira_wayland_resize_frame_create(
    void *display, void *surface, void *compositor, void *xdg_surface,
    int32_t width, int32_t height
) {
    struct wl_registry *registry = wl_display_get_registry(display);
    if (!registry) return 0;
    struct kira_wayland_resize_globals globals = {0};
    const struct wl_registry_listener listener = {
        .global = kira_wayland_resize_global,
        .global_remove = kira_wayland_resize_global_remove,
    };
    wl_registry_add_listener(registry, &listener, &globals);
    int ok = wl_display_roundtrip(display) >= 0;
    wl_registry_destroy(registry);
    if (!ok || !globals.subcompositor || !globals.shm || !globals.viewporter) return 0;

    int fd = memfd_create("kira-wayland-resize", MFD_CLOEXEC);
    if (fd < 0 || ftruncate(fd, 4) != 0) { if (fd >= 0) close(fd); return 0; }
    uint32_t *pixel = mmap(NULL, 4, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (pixel == MAP_FAILED) { close(fd); return 0; }
    *pixel = 0;

    struct kira_wayland_resize_frame *frame = calloc(1, sizeof(*frame));
    if (!frame) { munmap(pixel, 4); close(fd); return 0; }
    frame->root = surface;
    frame->xdg_surface = xdg_surface;
    frame->pool = wl_shm_create_pool(globals.shm, fd, 4);
    frame->buffer = wl_shm_pool_create_buffer(frame->pool, 0, 1, 1, 4, WL_SHM_FORMAT_ARGB8888);
    munmap(pixel, 4);
    close(fd);
    if (!frame->pool || !frame->buffer) { free(frame); return 0; }

    const uint32_t edges[KIRA_WAYLAND_RESIZE_ZONE_COUNT] = {
        XDG_TOPLEVEL_RESIZE_EDGE_TOP, XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM,
        XDG_TOPLEVEL_RESIZE_EDGE_LEFT, XDG_TOPLEVEL_RESIZE_EDGE_RIGHT,
        XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT, XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT,
        XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT, XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT,
    };
    for (int i = 0; i < KIRA_WAYLAND_RESIZE_ZONE_COUNT; ++i) {
        frame->edges[i] = edges[i];
        frame->zones[i] = wl_compositor_create_surface(compositor);
        frame->subsurfaces[i] = wl_subcompositor_get_subsurface(
            globals.subcompositor, frame->zones[i], surface
        );
        frame->viewports[i] = wp_viewporter_get_viewport(globals.viewporter, frame->zones[i]);
        if (!frame->zones[i] || !frame->subsurfaces[i] || !frame->viewports[i]) return 0;
    }
    frame->next = kira_wayland_resize_frames;
    kira_wayland_resize_frames = frame;
    kira_wayland_resize_frame_update(surface, width, height);
    wp_viewporter_destroy(globals.viewporter);
    wl_shm_destroy(globals.shm);
    wl_subcompositor_destroy(globals.subcompositor);
    return 1;
}

uint32_t kira_wayland_resize_frame_edge(void *surface, void *event_surface) {
    struct kira_wayland_resize_frame *frame = kira_wayland_resize_frame_find(surface);
    if (!frame) return 0;
    for (int i = 0; i < KIRA_WAYLAND_RESIZE_ZONE_COUNT; ++i)
        if (frame->zones[i] == event_surface) return frame->edges[i];
    return 0;
}

int32_t kira_wayland_resize_frame_offset_x(void *surface, void *event_surface) {
    struct kira_wayland_resize_frame *frame = kira_wayland_resize_frame_find(surface);
    if (!frame) return 0;
    for (int i = 0; i < KIRA_WAYLAND_RESIZE_ZONE_COUNT; ++i)
        if (frame->zones[i] == event_surface) return frame->offsets_x[i];
    return 0;
}

int32_t kira_wayland_resize_frame_offset_y(void *surface, void *event_surface) {
    struct kira_wayland_resize_frame *frame = kira_wayland_resize_frame_find(surface);
    if (!frame) return 0;
    for (int i = 0; i < KIRA_WAYLAND_RESIZE_ZONE_COUNT; ++i)
        if (frame->zones[i] == event_surface) return frame->offsets_y[i];
    return 0;
}

void kira_wayland_resize_frame_destroy(void *surface) {
    struct kira_wayland_resize_frame **link = &kira_wayland_resize_frames;
    while (*link && (*link)->root != surface) link = &(*link)->next;
    if (!*link) return;
    struct kira_wayland_resize_frame *frame = *link;
    *link = frame->next;
    for (int i = 0; i < KIRA_WAYLAND_RESIZE_ZONE_COUNT; ++i) {
        if (frame->viewports[i]) wp_viewport_destroy(frame->viewports[i]);
        if (frame->subsurfaces[i]) wl_subsurface_destroy(frame->subsurfaces[i]);
        if (frame->zones[i]) wl_surface_destroy(frame->zones[i]);
    }
    if (frame->buffer) wl_buffer_destroy(frame->buffer);
    if (frame->pool) wl_shm_pool_destroy(frame->pool);
    free(frame);
}

void kira_wayland_proxy_destroy(void *proxy) { wl_proxy_destroy(proxy); }
uint32_t kira_wayland_proxy_get_version(void *proxy) { return wl_proxy_get_version(proxy); }
void kira_wayland_proxy_set_user_data(void *proxy, void *data) { wl_proxy_set_user_data(proxy, data); }
void *kira_wayland_proxy_get_user_data(void *proxy) { return wl_proxy_get_user_data(proxy); }
void *kira_wayland_proxy_get_display(void *proxy) { return wl_proxy_get_display(proxy); }
