[library]
name = "directx12"
link_mode = "dynamic"
abi = "c"

[headers]
entrypoint = "${WINDOWS_KITS_10_INCLUDE}/um/d3d12.h"
include_dirs = ["${WINDOWS_KITS_10_INCLUDE}/um", "${WINDOWS_KITS_10_INCLUDE}/shared", "${WINDOWS_KITS_10_INCLUDE}/ucrt"]
defines = ["WIN32_LEAN_AND_MEAN", "NOMINMAX"]

[autobinding]
module = "directx12"
output = "../bindings/directx12/directx12.kira"
headers = ["${WINDOWS_KITS_10_INCLUDE}/um/d3d12.h", "${WINDOWS_KITS_10_INCLUDE}/um/d3d12sdklayers.h", "${WINDOWS_KITS_10_INCLUDE}/um/d3dcommon.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgi.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgi1_2.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgi1_3.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgi1_4.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgi1_5.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgi1_6.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgiformat.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgitype.h", "${WINDOWS_KITS_10_INCLUDE}/shared/dxgicommon.h", "${WINDOWS_KITS_10_INCLUDE}/shared/guiddef.h"]

[bindings]
profile = "directx12"
mode = "all_public"

[target.x86_64-windows-msvc]
dynamic_lib = ""
